export const CART_ACTION_TYPES = {
  SET_DISPLAYED: "cart/SET_DISPLAYED",
  SET_CURRENT_CART: "cart/SET_CURRENT_CART",
  SET_TOTAL_QUANTITY: "cart/SET_TOTAL_QUANTITY",
  SET_TOTAL_PRICE: "cart/SET_TOTAL_PRICE",
};